[package]
name = "longcat-frontend-desktop"
version = "0.2.0"
description = "LongCat-frontend Desktop (Tauri shell)"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
strip = true
lto = true
opt-level = "z"
panic = "abort"
